### ISSUE TITLE
Please redo PDF as MD

### ISSUE THREAD

**Issue by HadleyKing** [GW-HIVE/microbiome#1]
This file should be a `Curating_accessionList.md` not `Curating_accessionList.pdf`
https://github.com/GW-HIVE/microbiome/blob/master/Curating_accessionList.pdf

**Comment by jiugeyang** [comment]
I have redone the file as a markdown file. It is now `Curating_accessionList.md`
I have deleted the `Curating_accessionList.pdf`.

The new markdown file is listed here:[https://github.com/GW-HIVE/microbiome/blob/master/Curating_accessionList.md](url)

**Comment by HadleyKing** [comment]
Please reference a commit hash when you close an issue or comment on the status.

**Comment by HadleyKing** [comment]
a77ff30ee3a36c94ca07a62cced27a74971777be
