### ISSUE TITLE
Remove identifying info from scripts in repo

### ISSUE THREAD

**Issue by HadleyKing** [GW-HIVE/microbiome#2]
Remove identifying info from scripts in repo:
- https://github.com/GW-HIVE/microbiome/blob/b80131810c983d14e4c7c4483c5dbe0b16a57e44/TaxID.py#L12

- https://github.com/GW-HIVE/microbiome/blob/b80131810c983d14e4c7c4483c5dbe0b16a57e44/search.py#L13

**Comment by jiugeyang** [comment]
I have removed all identifying info from both scripts.

**Comment by HadleyKing** [comment]
fe30b52c0e2cd3c92104111526d27e5fac9bdf56
d4507224a52a446d9423ecccd6cb8074faf42e5c
